### ISSUE TITLE
Proper CLI by having terminal based GUI

### ISSUE THREAD

**Issue by vega-d** [AUNaseef/protonup#13]
I found this neat little library called asciimatics. 

https://github.com/peterbrittain/asciimatics

It can dynamically create ui inside of terminal, supports color displays and mouse input.
If something like pyqt4 or gi is too large of a dependency (though ui would look cooler with them), this lib is fairly smol - around 4 megabytes, while providing at least somewhat good UI

**Comment by DavidoTek** [comment]
For those looking for a "real" GUI, I made two using large dependencies. You can find them here:
- Using DearPyGUI: https://gist.github.com/DavidoTek/dec8cb0ce38b1e69c12fe178ea3d97cf
- Using PySide6 (AppImage available, ~221MB): https://github.com/DavidoTek/ProtonUp-Qt
