### ISSUE TITLE
Same Option For Wine-GE?

### ISSUE THREAD

**Issue by intelligentgaming** [AUNaseef/protonup#16]
Not really an issue, but did you consider doing the same thing for Wine-GE?

**Comment by Seibz** [comment]
The source for wine-ge [here](https://github.com/GloriousEggroll/wine-ge-custom/releases) would just need to be extracted to the `/home/USERNAME/.local/share/lutris/runners/wine/` folder I believe.

**Comment by Latrolage** [comment]
Might have to check if lutris follows the [XDG base directory](https://wiki.archlinux.org/title/XDG_Base_Directory) specification, in which case it won't always be at `~/.local/share/lutris`
