### ISSUE TITLE
Feature Request: Make accessible from Steamdeck UI in similar way to Chrome's Standalone Flatpak.

### ISSUE THREAD

**Issue by Daasin** [AUNaseef/protonup#27]
It's tappable from the home-screen and doesn't even need desktop mode either even to install. 

(Chrome Just involved clicking an automatic dialog box prompt that popped up when looking at non-steam apps section) 

It could make life so much easier for getting automatic updates on Steamdeck :) 🙏🏼

**Comment by Daasin** [comment]
@AUNaseef would it be possible to have that as an option from the app? Even if initially installing from desktop mode, allow it to launch as a non-steam shortcut from the tablet mode 🤔

**Comment by cloudishBenne** [comment]
@Daasin i think what you are looking for is called https://davidotek.github.io/protonup-qt/
If you want automatic updated GE-Proton, hope that the AUR gets updated to my fork (https://aur.archlinux.org/packages/protonup-git).

**Comment by Daasin** [comment]
> @Daasin i think what you are looking for is called https://davidotek.github.io/protonup-qt/ If you want automatic updated GE-Proton, hope that the AUR gets updated to my fork (https://aur.archlinux.org/packages/protonup-git).

Ah... Just realised 😅 
Im in the wrong repo, my apologies for the mistake!
