### ISSUE TITLE
NOTICE: THIS PROJECT IS UNMAINTAINED SINCE MONTHS -> install my fork protonup-ng

### ISSUE THREAD

**Issue by cloudishBenne** [AUNaseef/protonup#31]
Because this project is borked since months where the naming scheme of Proton-GE changed to GE-Proton (https://www.patreon.com/posts/63101415) and @AUNaseef didn't react to this here, i made a fork called **protonup-ng**. The tool already works with the new naming scheme.
After refactoring is done i want to fix some issues from over here, but enhancements will happen later. If you want to contribute, just ask or make a [pull request](https://github.com/cloudishBenne/protonup-ng/pulls) at my [repo](https://github.com/cloudishBenne/protonup-ng).

I hope @AUNaseef is alright and will be back soon! I will link all additions to his codebase with pull requests.

Links:
https://pypi.org/project/protonup-ng/
https://github.com/cloudishBenne/protonup-ng

**Comment by bitterhalt** [comment]
> Because this project is borked since weeks where the naming scheme of Proton-GE changed to GE-Proton (https://www.patreon.com/posts/63101415) and @AUNaseef didn't react to this here, i made a hopefully temporarily fork called **ProtonUp-ng**. The tool already works with the new naming scheme. After refactoring is done i want to fix some issues from over here, but enhancements will happen later. @kureta will help a bit, and if you want to contribute, just ask or make a pull request at my repo.
> 
> I hope @AUNaseef is alright and will be back soon! I will link all additions to his codebase with pull requests.
> 
> Links: https://pypi.org/project/protonup-ng/ https://github.com/cloudishBenne/protonup-ng

Thanks!

**Comment by AUNaseef** [comment]
I don't see any glaring issues with protonup so I think it's totally fine to use it as-is, even if it's not actively getting updates. therefore I am closing this issue.
