### ISSUE TITLE
how to fix protonup command not found

### ISSUE THREAD

**Issue by smartguy4321** [AUNaseef/protonup#35]
I saw that you have to add something to ~/.profile, but i really dont know what .profile is or where i can find it, i would like to solve this, thanks in advance.

**Comment by PoopaScoopa** [comment]
You probably don't need to add anything but if you do, go to view and under hidden files.  Once you enable that you can see it under your home and user directory.  For me I just had to type "source ~/.profile".  Once I did that, I typed protonup and gave me the option to download it.

**Comment by AUNaseef** [comment]
@smartguy4321 .profile file will be in your home directory, dot files are hidden by default.
enable 'show hidden files' in your file manager to see it. create one if you don't find it.
you can simpy run `nano ~/.profile` to edit it directly from any terminal window btw.
