### ISSUE TITLE
protonup installs to ~/.steam/root/compatibilitytools.d but Steam is only looking under ~/.local/share/steam

### ISSUE THREAD

**Issue by colemickens** [AUNaseef/protonup#40]
Hi,

I recently decided to try Steam in Linux again.

I noticed that `protonup` was installing the latest GE Proton to `~/.steam/root/compatibilituttools.d` but Steam was not noticing the custom Proton, and I couldn't select it in the UI.

However, after running this, Steam was able to find custom Proton:

```
cp -r ~/.steam/root/compatibilitytools.d ~/.local/share/Steam/
```

**Comment by AUNaseef** [comment]
You can change the default installation directory with  `-d`, in your case I guess it would be
`protonup -d "~/.local/share/Steam/compatibilitytools.d"`
