### ISSUE TITLE
other versions of proton ge

### ISSUE THREAD

**Issue by B-Nerd** [AUNaseef/protonup#5]
when listing all the version of proton ge with the command protonup -l it does not show up you need to "install" that version 
but after doing both show up

**Comment by AUNaseef** [comment]
`protonup -l` should list only the installed versions,
use `protonup --releases` to list all available proton-ge releases.

does this resolve the issue?

**Comment by B-Nerd** [comment]
don't know already fixed it

Vriendelijke Groet Benjamin van Ark

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by AUNaseef** [comment]
Good to know :)
